# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'a.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import getpass
from PyQt5 import QtCore, QtGui, QtWidgets
from crop import *
import os
import sys
import math
import time
import imghdr

class Ui_Form(object):
    def setupUi(self, Form):
        self.is_auto_update = True
        self.auto_update_delay = 3
        # self.auto_update()

        self.screenwidth = QtWidgets.QDesktopWidget().screenGeometry().width()
        self.screenheight = QtWidgets.QDesktopWidget().screenGeometry().height()
        Form.setObjectName("ANGLE VIEW")
        Form.resize(922, 522)
        Form.setFixedSize(Form.size())
        Form.move(self.screenwidth - Form.width(), self.screenheight - Form.height() - 60)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("new_screenshot.jpg"))
        self.label.setObjectName("label")
        self.label.mousePressEvent = self.getAngle
        self.horizontalLayout_2.addWidget(self.label)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_2.setStyleSheet("background-color: rgb(11, 11, 23);\n"
"color: rgb(255, 0, 0);\n"
"font-size: 36px;\n"
"font-weight: bold;\n"
"padding: 10px;")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_3.setStyleSheet("background-color: rgb(11, 11, 23);\n"
"color: rgb(255, 255, 255);\n"
"padding: 10px;")
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_4.setStyleSheet("background-color: rgb(11, 11, 23);\n"
"color: rgb(255, 255, 255);\n"
"padding: 10px;")
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_5.setStyleSheet("background-color: rgb(11, 11, 23);\n"
"color: rgb(255, 255, 255);\n"
"padding: 10px;")
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)

        self.label_6 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_6.setStyleSheet("background-color: rgb(11, 11, 23);\n"
"color: rgb(255, 255, 255);\n"
"padding: 10px;")
        self.label_6.setWordWrap(True) 
        self.label_6.setObjectName("label_6")
        
        self.verticalLayout.addWidget(self.label_6)
        self.listView = QtWidgets.QListView(Form)
        self.listView.setObjectName("listView")
        self.verticalLayout.addWidget(self.listView)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setStyleSheet("padding: 8px;\n"
"background-color: rgb(13, 0, 50);\n"
"color: rgb(255, 255, 255);\n"
"font: 12pt \"Calibri\";\n"
"border: 0px;\n"
"outline: 0px;")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setStyleSheet("padding: 8px;\n"
"background-color: rgb(13, 0, 50);\n"
"color: rgb(255, 255, 255);\n"
"font: 12pt \"Calibri\";\n"
"border: 0px;\n"
"outline: 0px;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setStyleSheet("padding: 8px;\n"
"background-color: rgb(13, 0, 50);\n"
"color: rgb(255, 255, 255);\n"
"font: 12pt \"Calibri\";\n"
"border: 0px;\n"
"outline: 0px;")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout)

        self.sty_dots = "QLabel#lblDots {\n" \
        "    background-color: #ff00ff;\n" \
        "    border-style: none;\n" \
        "    padding: 8px;\n" \
        "    font: bold 20px;\n" \
        "    border-width: 2px;\n" \
        "    border-radius: 0px;\n" \
        "    border-color: #2752B8;\n" \
        "    font-size: 14px;\n" \
        "}\n"

        self.lblDots = QtWidgets.QLabel(Form)
        self.lblDots.setGeometry(QtCore.QRect(266, 266, 3, 3))
        self.lblDots.setStyleSheet(self.sty_dots)
        self.lblDots.setObjectName("lblDots")
        
        self.lblDots2 = QtWidgets.QLabel(Form)
        self.lblDots2.setGeometry(QtCore.QRect(265, 27, 3, 20))
        self.lblDots2.setStyleSheet(self.sty_dots)
        self.lblDots2.setObjectName("lblDots")

        self.lblDots3 = QtWidgets.QLabel(Form)
        self.lblDots3.setGeometry(QtCore.QRect(473, 269, 20, 3))
        self.lblDots3.setStyleSheet(self.sty_dots)
        self.lblDots3.setObjectName("lblDots")

        self.lblDots4 = QtWidgets.QLabel(Form)
        self.lblDots4.setGeometry(QtCore.QRect(265, 473, 3, 20))
        self.lblDots4.setStyleSheet(self.sty_dots)
        self.lblDots4.setObjectName("lblDots")

        self.lblDots5 = QtWidgets.QLabel(Form)
        self.lblDots5.setGeometry(QtCore.QRect(34, 269, 20, 3))
        self.lblDots5.setStyleSheet(self.sty_dots)
        self.lblDots5.setObjectName("lblDots")

        self.lblPick = QtWidgets.QLabel(Form)
        self.lblPick.setGeometry(QtCore.QRect(266, 266, 2, 2))
        self.lblPick.setStyleSheet(self.sty_dots)
        self.lblPick.setObjectName("lblDots")

        self.pushButton.clicked.connect(self.crop_image)
        self.pushButton_2.clicked.connect(self.auto_update)
        self.pushButton_3.clicked.connect(self.pick_folder)

        self.folder_path = "C:\\Users\\" + getpass.getuser() + "\\Desktop\\"
        self.full_path = "C:\\Users\\" + getpass.getuser() + "\\Desktop\\"

        if self.is_auto_update:
            while self.is_auto_update:
                self.crop_image()
                time.sleep(self.auto_update_delay)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        # self.crop_image()

    def pick_folder(self):
        # get the last file from directory
        self.path = QtWidgets.QFileDialog.getExistingDirectory(None, 'Select a folder:', self.folder_path)
        if self.path != '':
            self.folder_path = self.path
            # get all files from the directory
            self.files = os.listdir(self.folder_path)
            # get the last file from the directory
            self.file = self.files[-1]
            # get the last file from the directory
            self.full_path = self.folder_path + '/' + self.file
            self.label_6.setText(str(self.folder_path))

            text_file = open("user_settings.txt", "w")
            n = text_file.write(str(self.folder_path))
            text_file.close()

     
    def getAngle(self, event):
        # get the mouse position
        x = event.x()
        y = event.y()
        self.lblPick.setGeometry(QtCore.QRect(x + 11, y + 11, 5, 5))
        # get the image width and height
        width = self.label.width()
        height = self.label.height()
        # get distance from the x axis
        xDistance = abs(int(x - width/2))
        # get distance from the y axis
        yDistance = abs(int(y - height/2))
        # get distance from the center
        distance = math.sqrt(xDistance**2 + yDistance**2)
        # get cos, sin, tan
        cos = xDistance/distance
        sin = yDistance/distance
        tan =  0 if xDistance == 0 else yDistance/xDistance
        # print("width = ", str(width), ", height = ", str(height))
        # print("cos = ", str(cos), ", sin = ", str(sin), ", tan = ", str(tan))
        # get angle in degrees
        angle = abs(math.degrees(math.atan(tan)) - 90)
        # print("angle = ", str(angle))
        self.label_2.setText(str(round(float(angle), 2)))
        # update label_4 text
        self.label_3.setText("COS " + str(cos))
        self.label_4.setText("SIN " + str(sin))
    
    def crop_image(self):

        self.image_path = "new_screenshot.jpg"
        self.files = os.listdir(self.folder_path)
        self.file = self.files[-1]

        try:
            with open('user_settings.txt') as f:
                lines = f.readlines()
                self.folder_path = lines[0]
                self.label_6.setText(lines[0])
                # f.close()
            print(self.label_6.text())
            print(self.folder_path)
            print(self.file)
            
            
            save_new_image(self.folder_path + '/' + self.file)
            self.label.setPixmap(QtGui.QPixmap("new_screenshot.jpg"))

        except Exception as e:
            print(e)
            self.is_auto_update = False

    def auto_update(self):
        if self.is_auto_update:
            self.is_auto_update = False
            self.label_5.setText("AUTO UPDATE: " + str(self.is_auto_update).upper())
        else:
            self.is_auto_update = True
            self.label_5.setText("AUTO UPDATE: " + str(self.is_auto_update).upper())
           
        
    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "AGNLE VIEW"))
        self.label_2.setText(_translate("Form", "000"))
        self.label_3.setText(_translate("Form", "COS"))
        self.label_4.setText(_translate("Form", "SIN"))
        self.label_5.setText(_translate("Form", "AUTO UPDATE: " + str(self.is_auto_update).upper()))
        self.label_6.setText(_translate("Form", "FOLDER"))
        self.pushButton.setText(_translate("Form", "UPDATE"))
        self.pushButton_2.setText(_translate("Form", "AUTO UPDATE"))
        self.pushButton_3.setText(_translate("Form", "FOLDER"))


if __name__ == "__main__":
    
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

    

