# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'r.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        self.screenwidth = QtWidgets.QDesktopWidget().screenGeometry().width()
        self.screenheight = QtWidgets.QDesktopWidget().screenGeometry().height()
        Form.resize(self.screenwidth, 22)
        Form.setWindowOpacity(0.3)
        Form.move(QtWidgets.QApplication.desktop().screen().rect().center() - Form.rect().center())
        Form.setWindowFlags(QtCore.Qt.FramelessWindowHint | QtCore.Qt.WindowStaysOnTopHint)
        Form.setStyleSheet("background-color: rgba(0, 0, 0, 0);")

        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)

        self.horizontalMain = QtWidgets.QGridLayout()
        self.horizontalMain.setObjectName("horizontalMain")
        for i in range(41):
            self.line = QtWidgets.QFrame(Form)
            
            self.line.setFixedWidth(33)
            self.line.setFrameShape(QtWidgets.QFrame.VLine)
            self.line.setObjectName("line")
            if i == 20:
                self.line.setFixedHeight(20)
                self.line.setStyleSheet("color: crimson;")
                self.horizontalMain.addWidget(self.line, 0, i, 1, 1)
            elif((i == 5) or (i == 15) or (i == 25) or (i == 35) or (i == 45)):
                self.line.setFixedHeight(12)
                self.line.setStyleSheet("color: white;")
                self.horizontalMain.addWidget(self.line, 0, i, 1, 1)
            elif i == 10 or i == 30:
                self.line.setFixedHeight(12)
                self.line.setStyleSheet("color: red;")
                self.horizontalMain.addWidget(self.line, 0, i, 1, 1)
            else:
                self.line.setFixedHeight(8)
                self.line.setStyleSheet("color: gray;")
                self.horizontalMain.addWidget(self.line, 0, i, 1, 1)

        self.horizontalLayout.addLayout(self.horizontalMain)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)

        

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
