# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\eucri\Documents\_XTQ\py-angle-view-3\m2.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AngleViewNikesniper(object):
    def setupUi(self, AngleViewNikesniper):
        AngleViewNikesniper.setObjectName("AngleViewNikesniper")
        AngleViewNikesniper.resize(272, 84)
        self.centralwidget = QtWidgets.QWidget(AngleViewNikesniper)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        AngleViewNikesniper.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AngleViewNikesniper)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 272, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        AngleViewNikesniper.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AngleViewNikesniper)
        self.statusbar.setObjectName("statusbar")
        AngleViewNikesniper.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(AngleViewNikesniper)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(AngleViewNikesniper)
        QtCore.QMetaObject.connectSlotsByName(AngleViewNikesniper)

    def retranslateUi(self, AngleViewNikesniper):
        _translate = QtCore.QCoreApplication.translate
        AngleViewNikesniper.setWindowTitle(_translate("AngleViewNikesniper", "MainWindow"))
        self.pushButton.setText(_translate("AngleViewNikesniper", "close ruler"))
        self.pushButton_2.setText(_translate("AngleViewNikesniper", "close angle"))
        self.menuFile.setTitle(_translate("AngleViewNikesniper", "File"))
        self.actionExit.setText(_translate("AngleViewNikesniper", "Exit"))
